/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be :

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even - valued terms.*/

//#include "pch.h"
#include <stdio.h>

int main()
{
	long int x, y, z;
	long long int sum = 0;

		x = 0;
		y = 1;
		do {
			printf("%ld\n", x);
			z = x + y;
			x = y;
			if ((x % 2)== 0)
				sum += x;
			y = z;
		} while (x < 4'000'000);
	printf("%lld\n", sum);
	return 0;
}
